<?xml version="1.0" encoding="utf-8"?>
<testsuite failures="1" name="tedge_mapper_az_negative" skipped="0" tests="1" time="3.01" timestamp="2022-06-09T07:10:14">
	<testcase classname="TedgeMapperAzError" name="tedge_mapper_az_negative">
		<failure message="FAILED: Grep on tedge_sub.out contains &quot;Invalid JSON&quot;" type="FAILED"/>
		<system-out>07:10:11 INFO  ==============================================================
07:10:11 INFO  Id:    tedge_mapper_az_negative
07:10:11 INFO  Dir:   tedge_mapper_az/
07:10:11 INFO  Title: Validate the Azure Mapper that publishes an error message on tedge/errors when it receives an invalid JSON message on tedge/measurements
07:10:11 INFO  ==============================================================
07:10:12 INFO  Executed sudo&lt;tedge_mapper_az&gt;, exit status 0
07:10:12 INFO  Started sudo&lt;tedge_sub&gt; with process id 19739
07:10:13 INFO  Executed sudo&lt;tedge_temp&gt;, exit status 0
07:10:13 INFO  Executed sudo&lt;kill_out&gt;, exit status 0
07:10:13 WARN  Grep on tedge_sub.out contains &quot;Invalid JSON&quot; ... failed [run.py:62]
07:10:13 INFO  
07:10:13 INFO  cleanup:
07:10:13 INFO  mapper_cleanup
07:10:14 INFO  Executed sudo&lt;tedge_mapper_az&gt;, exit status 0
07:10:14 INFO  
07:10:14 INFO  Test duration: 3.01 secs
07:10:14 INFO  Test final outcome:  FAILED
07:10:14 INFO  Test outcome reason: Grep on tedge_sub.out contains &quot;Invalid JSON&quot;
07:10:14 INFO  
</system-out>
	</testcase>
</testsuite>
