<?xml version="1.0" encoding="utf-8"?>
<testsuite failures="1" name="docker_plugin_remove_with_version" skipped="0" tests="1" time="4.62" timestamp="2022-06-22T19:39:09">
	<testcase classname="DockerPluginRemoveWithVersionTest" name="docker_plugin_remove_with_version">
		<failure message="BLOCKED: sudo&lt;docker_run&gt; returned non-zero exit code 125" type="BLOCKED"/>
		<system-out>19:39:04 INFO  ==============================================================
19:39:04 INFO  Id:    docker_plugin_remove_with_version
19:39:04 INFO  Dir:   plugin_docker/
19:39:04 INFO  Title: Validate docker plugin remove with version
19:39:04 INFO  ==============================================================
19:39:05 INFO  Executed sudo&lt;docker_images&gt;, exit status 0
19:39:05 INFO  Grep on file /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_remove_with_version/Output/linux/docker_images.out ... passed
19:39:07 WARN  Executed sudo&lt;docker_run&gt;, exit status 125
19:39:07 INFO  Contents of docker_run.err: 
  Unable to find image 'registry:2.7.1' locally
  docker: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.
  See 'docker run --help'.
  -----

19:39:07 WARN  sudo&lt;docker_run&gt; returned non-zero exit code 125 ... blocked 
19:39:07 WARN  Aborted test due to BLOCKED outcome
19:39:07 INFO  
19:39:07 INFO  cleanup:
19:39:07 INFO  Removing containers scheduled to be cleaned up: ['', '25493f1b2662', 'cd6c3cd2cb2c9de6b4b9331480a96dcfb76228e1e8c33df43faf8fc5d1922c1f\n']
19:39:08 WARN  Executed sudo&lt;containers_for_cleanup&gt;, exit status 1
19:39:08 INFO  Removing images scheduled to be cleaned up: ['registry', 'registry:2.7.1', 'registry']
19:39:09 INFO  Executed sudo&lt;containers_for_cleanup&gt;, exit status 0
19:39:09 INFO  
19:39:09 INFO  Test duration: 4.62 secs
19:39:09 INFO  Test final outcome:  BLOCKED
19:39:09 INFO  Test outcome reason: sudo&lt;docker_run&gt; returned non-zero exit code 125
19:39:09 INFO  
</system-out>
	</testcase>
</testsuite>
