2022-06-22 19:38:28,886 INFO  ==============================================================
2022-06-22 19:38:28,887 INFO  Id:    docker_plugin_remove_with_version
2022-06-22 19:38:28,888 INFO  Dir:   plugin_docker/
2022-06-22 19:38:28,889 INFO  Title: Validate docker plugin remove with version
2022-06-22 19:38:28,890 INFO  ==============================================================
2022-06-22 19:38:29,706 INFO  Executed sudo<docker_images>, exit status 0
2022-06-22 19:38:29,711 INFO  Grep on file /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_remove_with_version/Output/linux/docker_images.out ... passed
2022-06-22 19:38:32,241 WARN  Executed sudo<docker_run>, exit status 125
2022-06-22 19:38:32,246 INFO  Contents of docker_run.err: 
2022-06-22 19:38:32,247 INFO    Unable to find image 'registry:2.7.1' locally
2022-06-22 19:38:32,247 INFO    2.7.1: Pulling from library/registry
2022-06-22 19:38:32,248 INFO    docker: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.
2022-06-22 19:38:32,249 INFO    See 'docker run --help'.
2022-06-22 19:38:32,250 INFO    -----
2022-06-22 19:38:32,250 INFO  
2022-06-22 19:38:32,301 WARN  sudo<docker_run> returned non-zero exit code 125 ... blocked 
2022-06-22 19:38:32,302 WARN  Aborted test due to BLOCKED outcome
2022-06-22 19:38:32,306 INFO  
2022-06-22 19:38:32,307 INFO  cleanup:
2022-06-22 19:38:32,308 INFO  Removing containers scheduled to be cleaned up: ['', 'd58dd0bb7253']
2022-06-22 19:38:33,122 WARN  Executed sudo<containers_for_cleanup>, exit status 1
2022-06-22 19:38:33,124 INFO  Removing images scheduled to be cleaned up: ['registry', 'registry:2.7.1']
2022-06-22 19:38:33,936 INFO  Executed sudo<containers_for_cleanup>, exit status 0
2022-06-22 19:38:33,940 INFO  
2022-06-22 19:38:33,941 INFO  Test duration: 5.06 secs
2022-06-22 19:38:33,942 INFO  Test final outcome:  BLOCKED
2022-06-22 19:38:33,943 INFO  Test outcome reason: sudo<docker_run> returned non-zero exit code 125
2022-06-22 19:38:33,944 INFO  
