<?xml version="1.0" encoding="utf-8"?>
<testsuite failures="1" name="valid_device_id" skipped="0" tests="1" time="46.3" timestamp="2022-06-10T13:01:15">
	<testcase classname="ValidateValidDeviceId" name="valid_device_id">
		<failure message="FAILED: Grep on tedge_connect_c8y_test.out contains &quot;successful&quot;" type="FAILED"/>
		<system-out>13:00:29 INFO  ==============================================================
13:00:29 INFO  Id:    valid_device_id
13:00:29 INFO  Dir:   misc_features/
13:00:29 INFO  Title: Valid device ID
13:00:29 INFO  ==============================================================
13:00:29 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
13:00:30 INFO  Executed sudo&lt;create_cert_dir&gt;, exit status 0
13:00:30 INFO  Executed sudo&lt;change_owner_of_dir&gt;, exit status 0
13:00:31 INFO  Executed sudo&lt;set_cert_path&gt;, exit status 0
13:00:31 INFO  Executed sudo&lt;set_key_path&gt;, exit status 0
13:00:32 INFO  Executed sudo&lt;cert_create&gt;, exit status 0
13:00:33 INFO  Executed sudo&lt;cert_upload&gt;, exit status 0
13:00:59 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 24 secs
13:01:09 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
13:01:09 INFO  Grep on file tedge_connect_c8y.out ... passed
13:01:09 WARN  Grep on tedge_connect_c8y_test.out contains &quot;successful&quot; ... failed [run.py:108]
13:01:09 INFO  
13:01:09 INFO  cleanup:
13:01:13 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
13:01:14 INFO  Executed sudo&lt;unset_cert_path&gt;, exit status 0
13:01:14 INFO  Executed sudo&lt;unset_key_path&gt;, exit status 0
13:01:15 INFO  Executed sudo&lt;remove_cert_dir&gt;, exit status 0
13:01:15 INFO  
13:01:15 INFO  Test duration: 46.30 secs
13:01:15 INFO  Test final outcome:  FAILED
13:01:15 INFO  Test outcome reason: Grep on tedge_connect_c8y_test.out contains &quot;successful&quot;
13:01:15 INFO  
</system-out>
	</testcase>
</testsuite>
